### ISSUE TITLE
有发动三战的计划吗？闪击台湾？

### ISSUE THREAD

**Issue by wuweijian1997** [WhaleFell/SMSBoom#65]
大家给他来点挫折，加速他的成长。

**Comment by Lujango** [comment]
已经在筹集活动经费了

**Comment by WhaleFell** [comment]
还是希望和平，不希望战争。台海战争打起来双方都不好。倒不如保持现状罢了。

**Comment by wuweijian1997** [comment]
> 还是希望和平，不希望战争。台海战争打起来双方都不好。倒不如保持现状罢了。

你真的15岁么，感觉比25岁都成熟。。。不占用公共资源了。
